name: Trident
version: 0.0.2
description: >-
  The magic kernel manager.
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  http: ^0.13.4
  process_run: ^0.12.2+2
  system_info: ^1.0.1
  trident: ^1.0.0